dist: xenial
language: node_js
node_js: [node]
cache: yarn
script: [yarn test, yarn ci-lint]
before_deploy: yarn version --no-git-tag-version --new-version "$TRAVIS_TAG"
deploy:
  provider: npm
  skip_cleanup: true
  email: ezzatron+iconduit@gmail.com
  api_key:
    secure: secure: "XEonSez7xlTsKcCcGtV4JbPGThU8mrhqjjej/QXySiFL4XJRn8/QS3/3J3ZD84pYhDGGpD//zyLU9kilZyvjdhizgwOXnokoaJk5PjryCrWI3zzriXaervmq/iXRV0RlMcMgshzbhBMoOGLjkLWFIJqogB+DRGHlUs4NMKnzDjBaLtJM9T4EKQ+rnWM0KG4AFGf5X79Rmw5adZ9XHRJDE0yXn6vDZu/pMInjVaoMwI466EDIghQsDjAo9WXuC5an5m4NmJ01h0ZeHMreVSjMZUznrUlzqxqn6Quw1AzYoG7sg/s9VrE4ZT82LhpK+DwHQu/qMMDC9dpUYL5FFTROirwC8OBiMOmX7t2FFXqA40NU60zivhmmRkjcwjAo9FGTJ64VecIiEcQwEm4bw95Sxp7HedSHeexJfe2FAz/cA/8xQo8I98BNDCVCt5KqOPqY66Cfwf1e8ImJusQIRtwA4AfzWeFShW5GnsotM7dAbzMbQYca9OPFx8emZD9UKOU6qd5icpU+9Lh8dXR10nD9MlYe6nJse4L+uhO+4Uf89ZTBNJ0sK2KQaxHMXT/239X7zYXfQWS4y72Q5R0nN0Sh9TtX+3VxcdiQHadK2uaed3qsxPWv1vD7d/+FYgKaPOX94Cpnn5RQXC528nXKZAKocUCQDTzljyMJJ869RtO6YBo="
  on:
    tags: true
